name: Release
on:
  push:
    branches: main
env:
  GH_TOKEN: ${{ secrets.YALESITES_BUILD_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install semantic-release/exec
        run: npm install --save-dev @semantic-release/exec

      - name: Release
        run: npx semantic-release
